spring:
  application:
    name: oauth-service

  sleuth:
    sampler:
      probability: 1.0


server:
  port: 9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      shiro: debug

  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p})  %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"